import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// 获取入口点参数，默认为 src/main.ts，可通过 --entry=src-v2/main.ts 指定
const entryArg = process.argv.find(arg => arg.startsWith('--entry='));
const entryPoint = entryArg ? entryArg.replace('--entry=', '') : 'src/main.ts';

// 获取输出文件名
const outfileArg = process.argv.find(arg => arg.startsWith('--out='));
const outfile = outfileArg ? outfileArg.replace('--out=', '') : 'dist/main.js';

// CSS loader plugin for importing CSS files
const cssPlugin = {
	name: 'css-plugin',
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			const css = readFileSync(args.path, 'utf8');
			return {
				contents: `
					const style = document.createElement('style');
					style.textContent = ${JSON.stringify(css)};
					document.head.appendChild(style);
				`,
				loader: 'js'
			};
		});
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === "production");

console.log(`Building: ${entryPoint} -> ${outfile}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	plugins: [cssPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	minify: prod,
	treeShaking: true,
	outfile: outfile,
}).catch(() => process.exit(1));

if (prod) {
	await context.rebuild();
	console.log(`Build complete: ${outfile}`);
	process.exit(0);
} else {
	await context.watch();
	console.log('Watching for changes...');
}