import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, copyFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const prod = (process.argv[2] === "production");
const outDir = 'dist';

// 确保 dist 目录存在
if (!existsSync(outDir)) {
	mkdirSync(outDir, { recursive: true });
}

// 复制 manifest.json 到 dist
if (existsSync('manifest.json')) {
	copyFileSync('manifest.json', `${outDir}/manifest.json`);
	console.log(`Copied manifest.json`);
}

// 复制 icons.json 到 dist（用于动态加载）
if (existsSync('src/icons.json')) {
	copyFileSync('src/icons.json', `${outDir}/icons.json`);
	console.log(`Copied icons.json`);
}

// CSS plugin - 将 CSS 注入到 JS 中
const cssPlugin = {
	name: 'css-plugin',
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			const css = readFileSync(args.path, 'utf8');
			return {
				contents: `
					const style = document.createElement('style');
					style.textContent = ${JSON.stringify(css)};
					document.head.appendChild(style);
				`,
				loader: 'js'
			};
		});
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

console.log('Building main.js...');

await esbuild.build({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [cssPlugin],
	external: [
		"obsidian", "electron",
		"@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
		"@codemirror/language", "@codemirror/lint", "@codemirror/search",
		"@codemirror/state", "@codemirror/view",
		"@lezer/common", "@lezer/highlight", "@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	minify: prod,
	treeShaking: true,
	outfile: `${outDir}/main.js`,
}).catch(() => process.exit(1));

console.log('Build complete!');
process.exit(0);